#! /bin/bash

##
# Copyright (c) 2011 Robert Brewitz
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

NAME=mongodb
DESC="document oriented database"

PIDFILE="/var/run/$NAME.pid"

DAEMON=/usr/local/bin/mongod
DAEMON_OPTS="--pidfilepath $PIDFILE --logpath /var/log/mongodb/mongod.log --config /usr/local/conf/mongodb.conf run"
DAEMON_LOGFILE=/var/log/mongodb/daemon.log

test -x $DAEMON || exit 0

if [ ! -d "/data/db" ]; then
  echo "Please mount disk to /data and/or create /data directory. Then create /data/db directory."
  exit 0
fi

if [ ! -f "/usr/local/conf/mongodb.conf" ]; then
  echo "Mongodb.conf was not found in /usr/local/conf directory, check CloudsAlot mongodb/config directory for example configuration files."
  exit 0
fi

#set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --pidfile $PIDFILE --exec $DAEMON --start -- $DAEMON_OPTS >> $DAEMON_LOGFILE&
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --quiet --pidfile $PIDFILE --exec $DAEMON --stop
        echo "$NAME."
        ;;
  restart|force-reload)
        echo "Restarting $DESC: "
        start-stop-daemon --quiet --pidfile $PIDFILE --exec $DAEMON --stop
        sleep 5
        start-stop-daemon --pidfile $PIDFILE --exec $DAEMON --start -- $DAEMON_OPTS >> $DAEMON_LOGFILE&
        echo "$NAME."
        ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
